tee: kinibi[410/500]: Import tee/hardware/interfaces into soong namespaces
Fixes these errors occurring since commit bd967964d ("tee: Add a soong
namespace for tee/hardware/interfaces") (for others):

error: hardware/samsung_slsi-linaro/exynos/tee/kinibi500/system/TeeService/Android.bp:16:1: "libteeservice_server" depends on undefined module "vendor.trustonic.tee@1.1"
Module "libteeservice_server" is defined in namespace "hardware/samsung_slsi-linaro/exynos/tee/kinibi500" which can read these 3 namespaces: ["hardware/samsung_slsi-linaro/exynos/tee/kinibi500" "hardware/samsung_slsi-linaro/exynos/tee/kinibi500" "."]
Module "vendor.trustonic.tee@1.1" can be found in these namespaces: ["hardware/samsung_slsi-linaro/exynos/tee/hardware/interfaces"]
error: hardware/samsung_slsi-linaro/exynos/tee/kinibi410/TeeService/Android.bp:16:1: "libteeservice_server" depends on undefined module "vendor.trustonic.tee@1.0"
Module "libteeservice_server" is defined in namespace "hardware/samsung_slsi-linaro/exynos/tee/kinibi410" which can read these 3 namespaces: ["hardware/samsung_slsi-linaro/exynos/tee/kinibi410" "hardware/samsung_slsi-linaro/exynos/tee/kinibi410" "."]
Module "vendor.trustonic.tee@1.0" can be found in these namespaces: ["hardware/samsung_slsi-linaro/exynos/tee/hardware/interfaces"]

Change-Id: I05eda2554677fbf5710bde10cadff2905cba9be6